## Task 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
x=np.array([2,4,5,3,6,5,7])
y=np.array([35,60,20,50,50,55,60])
df=pd.DataFrame({'Weight':x,'Price':y})
df.head()

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [3]:
X=df['Weight']
Y=df['Price']
meanWeight=np.mean(X)
meanWeight

np.float64(4.571428571428571)

In [4]:
meanPrice=np.mean(Y)
meanPrice

np.float64(47.142857142857146)

In [5]:
m=(np.sum((X-meanWeight)*(Y-meanPrice)))/np.sum((X-meanWeight)**2)
m

np.float64(2.620967741935484)

In [6]:
c=meanPrice-m*meanWeight

In [7]:
c

np.float64(35.16129032258065)

In [8]:
#Predict for 6.5
m*6.5+c

np.float64(52.197580645161295)

## Task 2

In [9]:
df['Predicted']=m*X+c
df.head()

Weight  Price  Predicted
0       2     35  40.403226
1       4     60  45.645161
2       5     20  48.266129
3       3     50  43.024194
4       6     50  50.887097

In [10]:
df['Residuals']=df['Price']-df['Predicted']
df.head()

Weight  Price  Predicted  Residuals
0       2     35  40.403226  -5.403226
1       4     60  45.645161  14.354839
2       5     20  48.266129 -28.266129
3       3     50  43.024194   6.975806
4       6     50  50.887097  -0.887097

## Task 3

In [11]:
#MAE
mae=(np.sum(np.abs(Y-df['Predicted'])))/len(df)
mae

np.float64(9.87327188940092)

In [12]:
#MSE
mse=(np.sum((Y-df['Predicted'])**2))/len(df)
mse

np.float64(167.30990783410135)

## Final task

In [13]:
from sklearn.linear_model import LinearRegression 
reg = LinearRegression()

In [14]:
df2=pd.read_csv('assignment.csv')
df2

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [15]:
reg.fit(df2[['Weight']],df2[['Price']])

LinearRegression()

In [16]:
reg.predict([[6.5]])

C:\Users\Rifat\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[52.19758065]])

In [17]:
reg.coef_

array([[2.62096774]])

In [18]:
reg.intercept_

array([35.16129032])

In [19]:
df2['Predicted']=reg.predict(df2[['Weight']])
df2.head()

Weight  Price  Predicted
0       2     35  40.403226
1       4     60  45.645161
2       5     20  48.266129
3       3     50  43.024194
4       6     50  50.887097

In [20]:
df2['Residual']=df2['Price']-df2['Predicted']
df2.head()

Weight  Price  Predicted   Residual
0       2     35  40.403226  -5.403226
1       4     60  45.645161  14.354839
2       5     20  48.266129 -28.266129
3       3     50  43.024194   6.975806
4       6     50  50.887097  -0.887097

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [22]:
mae=mean_absolute_error(df[['Price']],df[['Predicted']])
mae

np.float64(9.87327188940092)

In [23]:
mse=mean_squared_error(df[['Price']],df[['Predicted']])
mse

np.float64(167.30990783410135)